// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
import Foundation

struct AVFileToolStrings {
    enum Key: Int, CaseIterable {
        case videoTrim, videoCrop, videoSpeed, videoJoin, videoFrames, videoSplit, videoRedact, videoCompress
        case audioTrim, audioNormalize, audioChannels, audioBleep, audioVisualizer
        case tools, start, end, speed, frame, allFrames, parts, cuts, loudness, peak, range, mono, leftGain, rightGain, addRange, still, waveform, seconds, original, result, preparing
        case detectSilence, timecode, preview
    }
    private let values: [String]
    subscript(_ key: Key) -> String { values[key.rawValue] }
    func label(_ tool: AVFileTool) -> String { values[AVFileTool.allCases.firstIndex(of: tool)!] }
    static func localized(_ language: AppLanguage) -> Self {
        let text: String
        switch language {
        case .enUS: text = "Trim video|Crop video|Change speed|Join videos|Export frames|Split video|Redact video|Compress video|Trim audio|Normalize audio|Mix channels|Bleep audio|Audio visualizer|Video and audio tools|Start|End|Speed|Frame time|All frames (up to 5,000)|Equal parts|Cut times, separated by commas|Loudness (LUFS)|True peak (dBTP)|Loudness range (LU)|Mono|Left gain|Right gain|Add time range|Choose still image|Waveform|Seconds|Original|Result|Preparing preview…|Detect silent endpoints|Seconds or timecode (hh:mm:ss:frame)|Preview selected range (up to 30 seconds)"
        case .ptBR: text = "Cortar vídeo|Recortar vídeo|Alterar velocidade|Unir vídeos|Exportar quadros|Dividir vídeo|Ocultar vídeo|Comprimir vídeo|Cortar áudio|Normalizar áudio|Mixar canais|Censurar áudio|Visualizador de áudio|Ferramentas de vídeo e áudio|Início|Fim|Velocidade|Tempo do quadro|Todos os quadros (até 5.000)|Partes iguais|Tempos de corte separados por vírgulas|Volume (LUFS)|Pico real (dBTP)|Faixa de volume (LU)|Mono|Ganho esquerdo|Ganho direito|Adicionar intervalo|Escolher imagem fixa|Forma de onda|Segundos|Original|Resultado|Preparando prévia…|Detectar silêncio nas pontas|Segundos ou código de tempo (hh:mm:ss:quadro)|Prévia do intervalo (até 30 segundos)"
        case .tr: text = "Videoyu kes|Videoyu kırp|Hızı değiştir|Videoları birleştir|Kareleri dışa aktar|Videoyu böl|Videoyu gizle|Videoyu sıkıştır|Sesi kes|Sesi normalleştir|Kanalları karıştır|Sesi sansürle|Ses görselleştirici|Video ve ses araçları|Başlangıç|Bitiş|Hız|Kare zamanı|Tüm kareler (en fazla 5.000)|Eşit parçalar|Virgülle ayrılmış kesme zamanları|Ses yüksekliği (LUFS)|Gerçek tepe (dBTP)|Ses aralığı (LU)|Mono|Sol kazanç|Sağ kazanç|Zaman aralığı ekle|Sabit resim seç|Dalga biçimi|Saniye|Orijinal|Sonuç|Önizleme hazırlanıyor…|Sessiz uçları algıla|Saniye veya zaman kodu (ss:dd:ss:kare)|Seçili aralığı önizle (30 saniyeye kadar)"
        case .ru: text = "Обрезать видео|Кадрировать видео|Изменить скорость|Объединить видео|Экспорт кадров|Разделить видео|Скрыть области видео|Сжать видео|Обрезать аудио|Нормализовать аудио|Микшировать каналы|Заглушить аудио|Визуализатор аудио|Инструменты видео и аудио|Начало|Конец|Скорость|Время кадра|Все кадры (до 5000)|Равные части|Моменты разреза через запятую|Громкость (LUFS)|Истинный пик (dBTP)|Диапазон громкости (LU)|Моно|Усиление слева|Усиление справа|Добавить интервал|Выбрать изображение|Осциллограмма|Секунды|Оригинал|Результат|Подготовка просмотра…|Найти тишину по краям|Секунды или таймкод (чч:мм:сс:кадр)|Просмотр интервала (до 30 секунд)"
        case .uk: text = "Обрізати відео|Кадрувати відео|Змінити швидкість|Об’єднати відео|Експорт кадрів|Розділити відео|Приховати області відео|Стиснути відео|Обрізати аудіо|Нормалізувати аудіо|Змішати канали|Заглушити аудіо|Візуалізатор аудіо|Інструменти відео й аудіо|Початок|Кінець|Швидкість|Час кадру|Усі кадри (до 5000)|Рівні частини|Час розрізів через кому|Гучність (LUFS)|Справжній пік (dBTP)|Діапазон гучності (LU)|Моно|Підсилення ліворуч|Підсилення праворуч|Додати інтервал|Вибрати зображення|Осцилограма|Секунди|Оригінал|Результат|Підготовка перегляду…|Знайти тишу на краях|Секунди або таймкод (гг:хх:сс:кадр)|Перегляд інтервалу (до 30 секунд)"
        case .sk: text = "Skrátiť video|Orezať video|Zmeniť rýchlosť|Spojiť videá|Exportovať snímky|Rozdeliť video|Zakryť video|Komprimovať video|Skrátiť zvuk|Normalizovať zvuk|Zmiešať kanály|Cenzurovať zvuk|Vizualizér zvuku|Nástroje videa a zvuku|Začiatok|Koniec|Rýchlosť|Čas snímky|Všetky snímky (do 5 000)|Rovnaké časti|Časy rezov oddelené čiarkami|Hlasitosť (LUFS)|Skutočná špička (dBTP)|Rozsah hlasitosti (LU)|Mono|Ľavé zosilnenie|Pravé zosilnenie|Pridať interval|Vybrať obrázok|Priebeh vlny|Sekundy|Originál|Výsledok|Príprava náhľadu…|Zistiť tiché konce|Sekundy alebo časový kód (hh:mm:ss:snímka)|Náhľad intervalu (do 30 sekúnd)"
        case .de: text = "Video kürzen|Video zuschneiden|Geschwindigkeit ändern|Videos verbinden|Bilder exportieren|Video teilen|Video schwärzen|Video komprimieren|Audio kürzen|Audio normalisieren|Kanäle mischen|Audio zensieren|Audiovisualisierung|Video- und Audiowerkzeuge|Anfang|Ende|Geschwindigkeit|Bildzeit|Alle Bilder (bis 5.000)|Gleiche Teile|Schnittzeiten durch Kommas getrennt|Lautheit (LUFS)|True Peak (dBTP)|Lautheitsbereich (LU)|Mono|Verstärkung links|Verstärkung rechts|Zeitbereich hinzufügen|Standbild wählen|Wellenform|Sekunden|Original|Ergebnis|Vorschau wird vorbereitet…|Stille Enden erkennen|Sekunden oder Zeitcode (hh:mm:ss:Bild)|Bereich vorhören (bis 30 Sekunden)"
        case .fr: text = "Rogner la durée vidéo|Recadrer la vidéo|Modifier la vitesse|Joindre les vidéos|Exporter les images|Diviser la vidéo|Masquer la vidéo|Compresser la vidéo|Rogner l’audio|Normaliser l’audio|Mixer les canaux|Censurer l’audio|Visualiseur audio|Outils vidéo et audio|Début|Fin|Vitesse|Temps de l’image|Toutes les images (5 000 max.)|Parts égales|Temps de coupe séparés par des virgules|Sonie (LUFS)|Crête réelle (dBTP)|Plage de sonie (LU)|Mono|Gain gauche|Gain droit|Ajouter un intervalle|Choisir une image fixe|Forme d’onde|Secondes|Original|Résultat|Préparation de l’aperçu…|Détecter le silence aux extrémités|Secondes ou timecode (hh:mm:ss:image)|Aperçu de l’intervalle (30 secondes max.)"
        case .es: text = "Recortar duración de vídeo|Recortar imagen de vídeo|Cambiar velocidad|Unir vídeos|Exportar fotogramas|Dividir vídeo|Ocultar vídeo|Comprimir vídeo|Recortar audio|Normalizar audio|Mezclar canales|Censurar audio|Visualizador de audio|Herramientas de vídeo y audio|Inicio|Fin|Velocidad|Tiempo del fotograma|Todos los fotogramas (hasta 5.000)|Partes iguales|Tiempos de corte separados por comas|Sonoridad (LUFS)|Pico real (dBTP)|Rango de sonoridad (LU)|Mono|Ganancia izquierda|Ganancia derecha|Añadir intervalo|Elegir imagen fija|Forma de onda|Segundos|Original|Resultado|Preparando vista previa…|Detectar silencio en los extremos|Segundos o código de tiempo (hh:mm:ss:fotograma)|Vista previa del intervalo (hasta 30 segundos)"
        case .it: text = "Taglia video|Ritaglia video|Cambia velocità|Unisci video|Esporta fotogrammi|Dividi video|Oscura video|Comprimi video|Taglia audio|Normalizza audio|Mixa canali|Censura audio|Visualizzatore audio|Strumenti video e audio|Inizio|Fine|Velocità|Tempo fotogramma|Tutti i fotogrammi (fino a 5.000)|Parti uguali|Tempi di taglio separati da virgole|Sonorità (LUFS)|Picco reale (dBTP)|Intervallo sonorità (LU)|Mono|Guadagno sinistro|Guadagno destro|Aggiungi intervallo|Scegli immagine fissa|Forma d’onda|Secondi|Originale|Risultato|Preparazione anteprima…|Rileva silenzio alle estremità|Secondi o timecode (hh:mm:ss:fotogramma)|Anteprima intervallo (fino a 30 secondi)"
        case .ja: text = "動画の長さを切り取り|動画を切り抜き|速度を変更|動画を結合|フレームを書き出し|動画を分割|動画を隠す|動画を圧縮|音声を切り取り|音量を正規化|チャンネルをミックス|音声を伏せる|音声ビジュアライザー|動画と音声ツール|開始|終了|速度|フレーム時刻|全フレーム（最大5,000）|均等分割数|分割時刻（カンマ区切り）|ラウドネス（LUFS）|トゥルーピーク（dBTP）|ラウドネス範囲（LU）|モノラル|左ゲイン|右ゲイン|時間範囲を追加|静止画像を選択|波形|秒|元のファイル|結果|プレビューを準備中…|両端の無音を検出|秒またはタイムコード（時:分:秒:フレーム）|選択範囲をプレビュー（最大30秒）"
        case .ko: text = "동영상 길이 자르기|동영상 영역 자르기|속도 변경|동영상 합치기|프레임 내보내기|동영상 분할|동영상 가리기|동영상 압축|오디오 자르기|오디오 정규화|채널 믹싱|오디오 검열음|오디오 시각화|동영상 및 오디오 도구|시작|끝|속도|프레임 시간|모든 프레임 (최대 5,000)|동일 분할 수|쉼표로 구분한 분할 시간|음량 (LUFS)|트루 피크 (dBTP)|음량 범위 (LU)|모노|왼쪽 게인|오른쪽 게인|시간 범위 추가|정지 이미지 선택|파형|초|원본|결과|미리보기 준비 중…|양 끝 무음 감지|초 또는 타임코드 (시:분:초:프레임)|선택 범위 미리보기 (최대 30초)"
        case .zhHans: text = "截取视频|裁剪视频|更改速度|合并视频|导出帧|拆分视频|遮盖视频|压缩视频|截取音频|音量标准化|混合声道|消音替换|音频可视化|视频与音频工具|开始|结束|速度|帧时间|所有帧（最多 5,000）|等分数量|逗号分隔的切割时间|响度（LUFS）|真峰值（dBTP）|响度范围（LU）|单声道|左增益|右增益|添加时间范围|选择静态图像|波形|秒|原始文件|结果|正在准备预览…|检测两端静音|秒数或时间码（时:分:秒:帧）|预览所选范围（最多 30 秒）"
        case .zhTW, .zhHK: text = "截取影片|裁切影片|更改速度|合併影片|匯出影格|分割影片|遮蓋影片|壓縮影片|截取音訊|音量標準化|混合聲道|消音替換|音訊視覺化|影片與音訊工具|開始|結束|速度|影格時間|所有影格（最多 5,000）|等分數量|逗號分隔的分割時間|響度（LUFS）|真峰值（dBTP）|響度範圍（LU）|單聲道|左增益|右增益|加入時間範圍|選擇靜態影像|波形|秒|原始檔案|結果|正在準備預覽…|偵測兩端靜音|秒數或時間碼（時:分:秒:影格）|預覽所選範圍（最多 30 秒）"
        }
        return Self(values: text.components(separatedBy: "|"))
    }
}
