// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct PDFToolStrings {
    enum Key: Int, CaseIterable {
        case tools, split, merge, organize, compress, metadata, add, save, cancel
        case moveUp, moveDown, rotate, duplicate, remove, reset, originals
        case compressionHint, metadataHint, dragHint, pages, title, author, subject, keywords, clearFields, singleDocument
        case readQR, noQR, copy, documentOrder, sortName, sameWidth, sameWidthHint, saveOrganized, pdfFiles
    }
    private let values: [String]
    subscript(_ key: Key) -> String { values[key.rawValue] }
    func label(_ tool: PDFTool) -> String {
        switch tool {
        case .split: return self[.split]
        case .merge: return self[.merge]
        case .organize: return self[.organize]
        case .compress: return self[.compress]
        case .metadata: return self[.metadata]
        case .readQR: return self[.readQR]
        }
    }
    static func localized(_ language: AppLanguage) -> Self {
        let text: String
        switch language {
        case .enUS: text = "PDF tools|Split PDF|Merge PDFs|Organize pages|Compress PDF|Metadata|Add PDFs|Save copy|Cancel|Move earlier|Move later|Rotate|Duplicate|Remove|Reset order|Copies are saved beside the originals.|Optimizes embedded images. File size may not decrease.|Edit standard document fields.|Hold Shift and Option while dragging PDFs to open tools.|%d pages|Title|Author|Subject|Keywords|Clear fields|Keep one PDF in the list to use this tool.|Read QR|No QR codes found.|Copy|Document order|Sort by name|Make all pages the same width|Pages are scaled proportionally to match the narrowest page; their heights may still differ.|Save organized PDF|%d PDF files"
        case .ptBR: text = "Ferramentas de PDF|Dividir PDF|Mesclar PDFs|Organizar páginas|Comprimir PDF|Metadados|Adicionar PDFs|Salvar cópia|Cancelar|Mover antes|Mover depois|Girar|Duplicar|Remover|Redefinir ordem|As cópias são salvas ao lado dos originais.|Otimiza imagens incorporadas. O tamanho pode não diminuir.|Edite os campos padrão do documento.|Segure Shift e Option ao arrastar PDFs para abrir as ferramentas.|%d páginas|Título|Autor|Assunto|Palavras-chave|Limpar campos|Mantenha um PDF na lista para usar esta ferramenta.|Ler QR|Nenhum código QR encontrado.|Copiar|Ordem dos documentos|Ordenar por nome|Deixar todas as páginas com a mesma largura|As páginas são dimensionadas proporcionalmente à mais estreita; as alturas podem variar.|Salvar PDF organizado|%d arquivos PDF"
        case .tr: text = "PDF araçları|PDF böl|PDF birleştir|Sayfaları düzenle|PDF sıkıştır|Üst veriler|PDF ekle|Kopyayı kaydet|İptal|Öne taşı|Arkaya taşı|Döndür|Çoğalt|Kaldır|Sırayı sıfırla|Kopyalar özgünlerin yanına kaydedilir.|Gömülü resimleri iyileştirir. Dosya boyutu azalmayabilir.|Standart belge alanlarını düzenleyin.|Araçlar için PDF sürüklerken Shift ve Option tuşlarını basılı tutun.|%d sayfa|Başlık|Yazar|Konu|Anahtar sözcükler|Alanları temizle|Bu araç için listede bir PDF bırakın.|QR oku|QR kodu bulunamadı.|Kopyala|Belge sırası|Ada göre sırala|Tüm sayfaları aynı genişliğe getir|Sayfalar en dar sayfaya orantılı ölçeklenir; yükseklikleri farklı olabilir.|Düzenlenmiş PDF kaydet|%d PDF dosyası"
        case .ru: text = "Инструменты PDF|Разделить PDF|Объединить PDF|Упорядочить страницы|Сжать PDF|Метаданные|Добавить PDF|Сохранить копию|Отмена|Переместить раньше|Переместить позже|Повернуть|Дублировать|Удалить|Сбросить порядок|Копии сохраняются рядом с оригиналами.|Оптимизирует встроенные изображения. Размер может не уменьшиться.|Измените стандартные поля документа.|Удерживайте Shift и Option при перетаскивании PDF для открытия инструментов.|Страниц: %d|Название|Автор|Тема|Ключевые слова|Очистить поля|Оставьте один PDF в списке для этого инструмента.|Считать QR|QR-коды не найдены.|Копировать|Порядок документов|По имени|Одинаковая ширина страниц|Страницы масштабируются по ширине самой узкой; высота может отличаться.|Сохранить упорядоченный PDF|Файлов PDF: %d"
        case .uk: text = "Інструменти PDF|Розділити PDF|Об’єднати PDF|Упорядкувати сторінки|Стиснути PDF|Метадані|Додати PDF|Зберегти копію|Скасувати|Перемістити раніше|Перемістити пізніше|Повернути|Дублювати|Видалити|Скинути порядок|Копії зберігаються поруч з оригіналами.|Оптимізує вбудовані зображення. Розмір може не зменшитися.|Редагуйте стандартні поля документа.|Утримуйте Shift і Option під час перетягування PDF для відкриття інструментів.|Сторінок: %d|Назва|Автор|Тема|Ключові слова|Очистити поля|Залиште один PDF у списку для цього інструмента.|Зчитати QR|QR-кодів не знайдено.|Копіювати|Порядок документів|За назвою|Однакова ширина сторінок|Сторінки пропорційно масштабуються до найвужчої; висота може відрізнятися.|Зберегти впорядкований PDF|Файлів PDF: %d"
        case .sk: text = "Nástroje PDF|Rozdeliť PDF|Zlúčiť PDF|Usporiadať strany|Komprimovať PDF|Metadáta|Pridať PDF|Uložiť kópiu|Zrušiť|Presunúť skôr|Presunúť neskôr|Otočiť|Duplikovať|Odstrániť|Obnoviť poradie|Kópie sa ukladajú vedľa originálov.|Optimalizuje vložené obrázky. Veľkosť sa nemusí zmenšiť.|Upravte štandardné polia dokumentu.|Pri ťahaní PDF podržte Shift a Option na otvorenie nástrojov.|%d strán|Názov|Autor|Predmet|Kľúčové slová|Vymazať polia|Pre tento nástroj ponechajte v zozname jeden PDF.|Čítať QR|Nenašli sa žiadne QR kódy.|Kopírovať|Poradie dokumentov|Zoradiť podľa názvu|Rovnaká šírka strán|Strany sa úmerne zmenšia na najužšiu; výšky sa môžu líšiť.|Uložiť usporiadaný PDF|%d súborov PDF"
        case .de: text = "PDF-Werkzeuge|PDF teilen|PDFs zusammenführen|Seiten ordnen|PDF komprimieren|Metadaten|PDFs hinzufügen|Kopie speichern|Abbrechen|Nach vorne|Nach hinten|Drehen|Duplizieren|Entfernen|Reihenfolge zurücksetzen|Kopien werden neben den Originalen gespeichert.|Optimiert eingebettete Bilder. Die Dateigröße kann unverändert bleiben.|Standardfelder des Dokuments bearbeiten.|Beim Ziehen von PDFs Shift und Option halten, um Werkzeuge zu öffnen.|%d Seiten|Titel|Autor|Betreff|Schlagwörter|Felder leeren|Für dieses Werkzeug eine PDF in der Liste behalten.|QR lesen|Keine QR-Codes gefunden.|Kopieren|Dokumentreihenfolge|Nach Namen sortieren|Alle Seiten gleich breit|Seiten werden proportional an die schmalste angepasst; Höhen können abweichen.|Geordnetes PDF speichern|%d PDF-Dateien"
        case .fr: text = "Outils PDF|Diviser le PDF|Fusionner les PDF|Organiser les pages|Compresser le PDF|Métadonnées|Ajouter des PDF|Enregistrer une copie|Annuler|Déplacer avant|Déplacer après|Pivoter|Dupliquer|Supprimer|Réinitialiser l’ordre|Les copies sont enregistrées à côté des originaux.|Optimise les images intégrées. La taille peut ne pas diminuer.|Modifiez les champs standard du document.|Maintenez Maj et Option en glissant des PDF pour ouvrir les outils.|%d pages|Titre|Auteur|Sujet|Mots-clés|Effacer les champs|Gardez un seul PDF dans la liste pour cet outil.|Lire QR|Aucun code QR trouvé.|Copier|Ordre des documents|Trier par nom|Même largeur pour toutes les pages|Les pages sont ajustées proportionnellement à la plus étroite ; les hauteurs peuvent varier.|Enregistrer le PDF organisé|%d fichiers PDF"
        case .es: text = "Herramientas PDF|Dividir PDF|Combinar PDF|Organizar páginas|Comprimir PDF|Metadatos|Añadir PDF|Guardar copia|Cancelar|Mover antes|Mover después|Girar|Duplicar|Eliminar|Restablecer orden|Las copias se guardan junto a los originales.|Optimiza imágenes incrustadas. El tamaño puede no disminuir.|Edita los campos estándar del documento.|Mantén Mayús y Opción al arrastrar PDF para abrir las herramientas.|%d páginas|Título|Autor|Asunto|Palabras clave|Borrar campos|Deja un PDF en la lista para usar esta herramienta.|Leer QR|No se encontraron códigos QR.|Copiar|Orden de documentos|Ordenar por nombre|Igualar el ancho de las páginas|Las páginas se ajustan proporcionalmente a la más estrecha; sus alturas pueden variar.|Guardar PDF organizado|%d archivos PDF"
        case .it: text = "Strumenti PDF|Dividi PDF|Unisci PDF|Organizza pagine|Comprimi PDF|Metadati|Aggiungi PDF|Salva copia|Annulla|Sposta prima|Sposta dopo|Ruota|Duplica|Rimuovi|Ripristina ordine|Le copie vengono salvate accanto agli originali.|Ottimizza le immagini incorporate. Le dimensioni potrebbero non diminuire.|Modifica i campi standard del documento.|Tieni premuti Maiusc e Opzione mentre trascini PDF per aprire gli strumenti.|%d pagine|Titolo|Autore|Oggetto|Parole chiave|Svuota campi|Mantieni un PDF nell’elenco per usare questo strumento.|Leggi QR|Nessun codice QR trovato.|Copia|Ordine documenti|Ordina per nome|Stessa larghezza per tutte le pagine|Le pagine vengono ridimensionate proporzionalmente alla più stretta; le altezze possono variare.|Salva PDF organizzato|%d file PDF"
        case .ja: text = "PDFツール|PDFを分割|PDFを結合|ページを整理|PDFを圧縮|メタデータ|PDFを追加|コピーを保存|キャンセル|前へ移動|後へ移動|回転|複製|削除|順序をリセット|コピーは元ファイルの隣に保存されます。|埋め込み画像を最適化します。サイズが小さくならない場合があります。|文書の標準項目を編集します。|PDFをドラッグ中にShiftとOptionを押すとツールが開きます。|%dページ|タイトル|作成者|件名|キーワード|項目を消去|このツールではリストにPDFを1つ残してください。|QRを読み取る|QRコードが見つかりません。|コピー|文書の順序|名前順に並べる|全ページの幅を揃える|最も狭いページに合わせて比例縮小します。高さは異なる場合があります。|整理したPDFを保存|%d個のPDFファイル"
        case .ko: text = "PDF 도구|PDF 분할|PDF 병합|페이지 정리|PDF 압축|메타데이터|PDF 추가|사본 저장|취소|앞으로 이동|뒤로 이동|회전|복제|제거|순서 재설정|사본은 원본 옆에 저장됩니다.|포함된 이미지를 최적화합니다. 크기가 줄지 않을 수 있습니다.|표준 문서 필드를 편집합니다.|PDF를 드래그하면서 Shift와 Option을 누르면 도구가 열립니다.|%d페이지|제목|작성자|주제|키워드|필드 지우기|이 도구를 사용하려면 목록에 PDF 하나만 남기세요.|QR 읽기|QR 코드를 찾지 못했습니다.|복사|문서 순서|이름순 정렬|모든 페이지의 너비 맞추기|가장 좁은 페이지에 비례하여 크기를 조정합니다. 높이는 다를 수 있습니다.|정리한 PDF 저장|%d개 PDF 파일"
        case .zhHans: text = "PDF 工具|拆分 PDF|合并 PDF|整理页面|压缩 PDF|元数据|添加 PDF|保存副本|取消|向前移动|向后移动|旋转|复制|移除|重置顺序|副本保存在原文件旁边。|优化嵌入图像，文件大小可能不会减小。|编辑标准文档字段。|拖移 PDF 时按住 Shift 和 Option 以打开工具。|%d 页|标题|作者|主题|关键词|清空字段|请在列表中保留一个 PDF 以使用此工具。|读取 QR|未找到 QR 码。|复制|文档顺序|按名称排序|统一所有页面宽度|按最窄页面等比缩放，高度可能不同。|保存整理后的 PDF|%d 个 PDF 文件"
        case .zhTW, .zhHK: text = "PDF 工具|分割 PDF|合併 PDF|整理頁面|壓縮 PDF|中繼資料|加入 PDF|儲存副本|取消|向前移動|向後移動|旋轉|複製|移除|重設順序|副本儲存在原始檔旁。|最佳化嵌入影像，檔案大小可能不會減少。|編輯標準文件欄位。|拖移 PDF 時按住 Shift 和 Option 以開啟工具。|%d 頁|標題|作者|主題|關鍵字|清空欄位|請在清單中保留一個 PDF 以使用此工具。|讀取 QR|找不到 QR 碼。|複製|文件順序|依名稱排序|統一所有頁面寬度|依最窄頁面等比例縮放，高度可能不同。|儲存整理後的 PDF|%d 個 PDF 檔案"
        }
        return Self(values: text.components(separatedBy: "|"))
    }
}
